### ISSUE TITLE
command line no use --split   error  ,want setting "Send all traffic over VPN connection"

### ISSUE THREAD

**Issue by creaplus** [halo/macosvpn#43] opened 2020-01-28 12:33 UTC
When I created the l2tp VPN, I did not use the "--split" option to make all traffic go through the VPN. The Settings window has checked "Send all traffic over VPN connection", but the IP of my public network has not changed. The problem was solved by manually canceling and selecting again

OS: Catalina

**Comment by halo** [comment] 2020-01-28 19:40
Good catch!! And thank you for reporting the issue.

I did not notice this error because I'm not actively using any L2TP VPN at the moment. The checkbox looked fine in the GUI, but the GUI didn't care whether the underlying setting was a String `"1"` or a Number `1`. I was never really sure about this.

In the version you tried, I only created a String, but it has to be a Number. This issue surfaced when I refactored the codebase from Objective-C to Swift recently.

<img width="401" alt="Screen Shot 2020-01-28 at 19 20 47" src="https://user-images.githubusercontent.com/11441/73298241-3c2fe000-420d-11ea-8814-65cf2bcde5f2.png">

It's [fixed now](https://github.com/halo/macosvpn/commit/d0f41ca858e5bf2226e42a9918aaee58c1626381#diff-127834a91fa46ef21785286cc17ad3f3L108-L113) and I released 1.0.2, you can download it [here](https://github.com/halo/macosvpn/releases/tag/1.0.2). I also added regression tests so this won't be an issue in the future. Tests are [passing](https://travis-ci.org/halo/macosvpn).

I expect it to be promoted to homebrew by someone soon. Maybe you can volunteer for that :D

I'll close this for now, feel free to contact me if you encounter any problems.

Thank you again.

**Closed by halo** 2020-01-28 19:40 UTC

**Comment by halo** [comment] 2020-01-30 11:28
PS: Version `1.0.2` was quickly propagated to homebrew thanks to @tiiiecherle !
