### ISSUE TITLE
Saving Passwords

### ISSUE THREAD

**Issue by dev-manager-uk** [halo/macosvpn#48] opened 2021-01-11 09:44 UTC
This is an awesome tool, thank you for building it.

Is there a way to get macos to save the password?  

At the moment I seem to have to enter the password every time the computer wakes from sleep.

**Comment by halo** [comment] 2021-01-11 10:48
Hi! Thanks for reaching out!

This is your administrator password, there is no safe place to store it :) I could store it in the system keychain, but then there would still be no access to it, because the keychain is itself locked with your administrator password.

Technically, it might be possible to accept the password as a command line argument, but that's terrible practice, because your password would show up in your plaintext bash history.

Maybe there is a way to pipe it in from `stdin`. The mechanism to obtain authorization is [over here](https://github.com/halo/macosvpn/blob/f7715949ff16a9c2c55563d157451b9c6feeb930/macosvpn/Classes/Authorizations.swift#L24-L38) and really not that complex. However, it's baked into macOS for the end-user to type in, so I don't think I'll be able to obtain sudo just by providing the password to the operating system.

I'll have to think about this, or rather, google my way around :) Meanwhile, if you come up with an idea, do share it.

**Comment by halo** [comment] 2021-01-11 10:50
> At the moment I seem to have to enter the password every time the computer wakes from sleep.

This is because the sudo-session is remembered for some time. If you type `sudo whoami`, it will also not ask you for a password for some time.

**Comment by dev-manager-uk** [comment] 2021-01-11 11:25
These guys fixed with a clipboard hack!  [https://gist.github.com/adgedenkers/3874427](https://gist.github.com/adgedenkers/3874427)

)It seems to be a very common problem that lots of people are frustrated with:
[https://superuser.com/questions/342702/how-to-auto-save-a-cisco-vpn-connection-password-on-mac-os-x](https://superuser.com/questions/342702/how-to-auto-save-a-cisco-vpn-connection-password-on-mac-os-x)

**Comment by dev-manager-uk** [comment] 2021-01-11 12:23
ahh no, no the sudo/admin password.  I mean when you make the VPN connection you get a modal asking you for the vpn user password.  Are you not getting that each time?

**Comment by halo** [comment] 2021-01-11 12:28
I realized you meant that 😄 

To my knowledge, what you're experiencing is a problem that only occurs on some computers. I had this myself over the years on a few Macbooks every now and then. And I always got rid of it in the end. But it took either a clean operating system installation, some lucky update, or debugging some keychain problem.

I'm sorry, there is no scientific approach I can recommend for the procedure 😄

**Comment by halo** [comment] 2021-01-11 12:30
For what it's worth, this could well be caused by `macosvpn` if you use a broken version and the password is not properly stored in the keychain. Which macOS version and which macosvpn version are you using?

**Comment by dev-manager-uk** [comment] 2021-01-11 12:35
I'm on a brand new install of Big Sur on a 2019 Macbook Air with the latest homebrew install of macosvpn.

**Comment by halo** [comment] 2021-01-17 08:31
* Is this an L2TP or a Cisco service?
* Are you on Intel or M1?
* Does it work, when you create the service manually?

If it does not work with a manually created service, there is nothing I can do.

If it does work with a manual service, but not with a service created with `macosvpn` then we'd start debugging.

In [this section](https://github.com/halo/macosvpn#development) there are two commands. One will show you the internal data of all network (VPN) services on your machine. The other will show you the internal data of all keychain items (i.e. passwords stored on your computer).

You can compare the VPN service that works with one that does not work. Notice the strings that end with `.SS` and `.XAUTH`. 

<img width="756" alt="Screen Shot 2021-01-17 at 09 25 22" src="https://user-images.githubusercontent.com/11441/104835350-4e83ad80-58a6-11eb-97c1-329122f529f5.png">

Those are references to the passwords in your keychain (you get those with the other command).

<img width="605" alt="Screen Shot 2021-01-17 at 09 29 15" src="https://user-images.githubusercontent.com/11441/104835374-796e0180-58a6-11eb-975c-1608e5e0cd49.png">

So I'd look for oddities in that data, comparing one service that works and one that does not work. I would compare an L2TP service with an L2TP service. Alternatively a Cisco service with a Cisco service.

That's my brainstorming so far :) The first step is really to find out whether you can have any VPN connection at all that works properly.

**Comment by halo** [comment] 2021-04-08 17:52
Closing for now. Let me know if something new surfaces. 👍🏻

**Closed by halo** 2021-04-08 17:52 UTC
